name: Docker Image CI

on:
  push:
    branches: [ "local" ]
  pull_request:
    branches: [ "local" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag frank/gitea:$(date +%s)
